<?php
/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/


// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  0 => 
  array (
    'acceptable_sugar_versions' => 
    array (
      0 => '',
    ),
  ),
  1 => 
  array (
    'acceptable_sugar_flavors' => 
    array (
      0 => 'PRO',
    ),
  ),
  'readme' => 'Clone of the current account module, used to display agency data.',
  'key' => 'Agenc',
  'author' => 'Ryan',
  'description' => 'Agency module, similar to accounts.',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'Agencies',
  'published_date' => '2013-09-20 03:14:14',
  'type' => 'module',
  'version' => 1379646854,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'Agencies',
  'beans' => 
  array (
    0 => 
    array (
      'module' => 'Agenc_Agencies',
      'class' => 'Agenc_Agencies',
      'path' => 'modules/Agenc_Agencies/Agenc_Agencies.php',
      'tab' => true,
    ),
  ),
  'layoutdefs' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/agenc_agencies_accounts_Agenc_Agencies.php',
      'to_module' => 'Agenc_Agencies',
    ),
  ),
  'relationships' => 
  array (
    0 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/agenc_agencies_accountsMetaData.php',
    ),
  ),
  'image_dir' => '<basepath>/icons',
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/modules/Agenc_Agencies',
      'to' => 'modules/Agenc_Agencies',
    ),
  ),
  'language' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'en_us',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'bg_BG',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'da_DK',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'de_DE',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'es_ES',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'fr_FR',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'hu_HU',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'it_it',
    ),
    8 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'lt_LT',
    ),
    9 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'ja_JP',
    ),
    10 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'nb_NO',
    ),
    11 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'nl_NL',
    ),
    12 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'pt_PT',
    ),
    13 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'ro_RO',
    ),
    14 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'ru_RU',
    ),
    15 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'sv_SE',
    ),
    16 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'tr_TR',
    ),
    17 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'zh_CN',
    ),
    18 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'cs_CZ',
    ),
    19 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'et_EE',
    ),
    20 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'he_IL',
    ),
    21 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'pl_PL',
    ),
    22 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'pt_BR',
    ),
    23 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'ca_ES',
    ),
    24 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'en_UK',
    ),
    25 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'sr_RS',
    ),
    26 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Accounts.php',
      'to_module' => 'Accounts',
      'language' => 'lv_LV',
    ),
    27 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Agenc_Agencies.php',
      'to_module' => 'Agenc_Agencies',
      'language' => 'en_us',
    ),
    28 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Agenc_Agencies.php',
      'to_module' => 'Agenc_Agencies',
      'language' => 'bg_BG',
    ),
    29 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Agenc_Agencies.php',
      'to_module' => 'Agenc_Agencies',
      'language' => 'da_DK',
    ),
    30 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Agenc_Agencies.php',
      'to_module' => 'Agenc_Agencies',
      'language' => 'de_DE',
    ),
    31 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Agenc_Agencies.php',
      'to_module' => 'Agenc_Agencies',
      'language' => 'es_ES',
    ),
    32 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Agenc_Agencies.php',
      'to_module' => 'Agenc_Agencies',
      'language' => 'fr_FR',
    ),
    33 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Agenc_Agencies.php',
      'to_module' => 'Agenc_Agencies',
      'language' => 'hu_HU',
    ),
    34 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Agenc_Agencies.php',
      'to_module' => 'Agenc_Agencies',
      'language' => 'it_it',
    ),
    35 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Agenc_Agencies.php',
      'to_module' => 'Agenc_Agencies',
      'language' => 'lt_LT',
    ),
    36 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Agenc_Agencies.php',
      'to_module' => 'Agenc_Agencies',
      'language' => 'ja_JP',
    ),
    37 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Agenc_Agencies.php',
      'to_module' => 'Agenc_Agencies',
      'language' => 'nb_NO',
    ),
    38 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Agenc_Agencies.php',
      'to_module' => 'Agenc_Agencies',
      'language' => 'nl_NL',
    ),
    39 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Agenc_Agencies.php',
      'to_module' => 'Agenc_Agencies',
      'language' => 'pt_PT',
    ),
    40 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Agenc_Agencies.php',
      'to_module' => 'Agenc_Agencies',
      'language' => 'ro_RO',
    ),
    41 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Agenc_Agencies.php',
      'to_module' => 'Agenc_Agencies',
      'language' => 'ru_RU',
    ),
    42 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Agenc_Agencies.php',
      'to_module' => 'Agenc_Agencies',
      'language' => 'sv_SE',
    ),
    43 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Agenc_Agencies.php',
      'to_module' => 'Agenc_Agencies',
      'language' => 'tr_TR',
    ),
    44 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Agenc_Agencies.php',
      'to_module' => 'Agenc_Agencies',
      'language' => 'zh_CN',
    ),
    45 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Agenc_Agencies.php',
      'to_module' => 'Agenc_Agencies',
      'language' => 'cs_CZ',
    ),
    46 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Agenc_Agencies.php',
      'to_module' => 'Agenc_Agencies',
      'language' => 'et_EE',
    ),
    47 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Agenc_Agencies.php',
      'to_module' => 'Agenc_Agencies',
      'language' => 'he_IL',
    ),
    48 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Agenc_Agencies.php',
      'to_module' => 'Agenc_Agencies',
      'language' => 'pl_PL',
    ),
    49 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Agenc_Agencies.php',
      'to_module' => 'Agenc_Agencies',
      'language' => 'pt_BR',
    ),
    50 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Agenc_Agencies.php',
      'to_module' => 'Agenc_Agencies',
      'language' => 'ca_ES',
    ),
    51 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Agenc_Agencies.php',
      'to_module' => 'Agenc_Agencies',
      'language' => 'en_UK',
    ),
    52 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Agenc_Agencies.php',
      'to_module' => 'Agenc_Agencies',
      'language' => 'sr_RS',
    ),
    53 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Agenc_Agencies.php',
      'to_module' => 'Agenc_Agencies',
      'language' => 'lv_LV',
    ),
    54 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/zh_CN.lang.php',
      'to_module' => 'application',
      'language' => 'zh_CN',
    ),
    55 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/bg_BG.lang.php',
      'to_module' => 'application',
      'language' => 'bg_BG',
    ),
    56 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/tr_TR.lang.php',
      'to_module' => 'application',
      'language' => 'tr_TR',
    ),
    57 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/cs_CZ.lang.php',
      'to_module' => 'application',
      'language' => 'cs_CZ',
    ),
    58 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/en_UK.lang.php',
      'to_module' => 'application',
      'language' => 'en_UK',
    ),
    59 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/lt_LT.lang.php',
      'to_module' => 'application',
      'language' => 'lt_LT',
    ),
    60 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/da_DK.lang.php',
      'to_module' => 'application',
      'language' => 'da_DK',
    ),
    61 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/lv_LV.lang.php',
      'to_module' => 'application',
      'language' => 'lv_LV',
    ),
    62 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/nb_NO.lang.php',
      'to_module' => 'application',
      'language' => 'nb_NO',
    ),
    63 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/sv_SE.lang.php',
      'to_module' => 'application',
      'language' => 'sv_SE',
    ),
    64 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/hu_HU.lang.php',
      'to_module' => 'application',
      'language' => 'hu_HU',
    ),
    65 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/he_IL.lang.php',
      'to_module' => 'application',
      'language' => 'he_IL',
    ),
    66 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/es_ES.lang.php',
      'to_module' => 'application',
      'language' => 'es_ES',
    ),
    67 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/et_EE.lang.php',
      'to_module' => 'application',
      'language' => 'et_EE',
    ),
    68 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/ca_ES.lang.php',
      'to_module' => 'application',
      'language' => 'ca_ES',
    ),
    69 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/fr_FR.lang.php',
      'to_module' => 'application',
      'language' => 'fr_FR',
    ),
    70 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/ja_JP.lang.php',
      'to_module' => 'application',
      'language' => 'ja_JP',
    ),
    71 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/nl_NL.lang.php',
      'to_module' => 'application',
      'language' => 'nl_NL',
    ),
    72 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/en_us.lang.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
    73 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/it_it.lang.php',
      'to_module' => 'application',
      'language' => 'it_it',
    ),
    74 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/sr_RS.lang.php',
      'to_module' => 'application',
      'language' => 'sr_RS',
    ),
    75 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/ru_RU.lang.php',
      'to_module' => 'application',
      'language' => 'ru_RU',
    ),
    76 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/pl_PL.lang.php',
      'to_module' => 'application',
      'language' => 'pl_PL',
    ),
    77 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/de_DE.lang.php',
      'to_module' => 'application',
      'language' => 'de_DE',
    ),
    78 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/pt_BR.lang.php',
      'to_module' => 'application',
      'language' => 'pt_BR',
    ),
    79 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/pt_PT.lang.php',
      'to_module' => 'application',
      'language' => 'pt_PT',
    ),
    80 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/ro_RO.lang.php',
      'to_module' => 'application',
      'language' => 'ro_RO',
    ),
  ),
  'vardefs' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/agenc_agencies_accounts_Accounts.php',
      'to_module' => 'Accounts',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/agenc_agencies_accounts_Agenc_Agencies.php',
      'to_module' => 'Agenc_Agencies',
    ),
  ),
  'layoutfields' => 
  array (
    0 => 
    array (
      'additional_fields' => 
      array (
        'Accounts' => 'agenc_agencies_accounts_name',
      ),
    ),
  ),
  'wireless_subpanels' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/wirelesslayoutdefs/agenc_agencies_accounts_Agenc_Agencies.php',
      'to_module' => 'Agenc_Agencies',
    ),
  ),
);