<?PHP
/*********************************************************************************
 * The contents of this file are subject to the SugarCRM Professional Subscription
 * Agreement ("License") which can be viewed at
 * http://www.sugarcrm.com/crm/products/sugar-professional-eula.html
 * By installing or using this file, You have unconditionally agreed to the
 * terms and conditions of the License, and You may not use this file except in
 * compliance with the License.  Under the terms of the license, You shall not,
 * among other things: 1) sublicense, resell, rent, lease, redistribute, assign
 * or otherwise transfer Your rights to the Software, and 2) use the Software
 * for timesharing or service bureau purposes such as hosting the Software for
 * commercial gain and/or for the benefit of a third party.  Use of the Software
 * may be subject to applicable fees and any use of the Software without first
 * paying applicable fees is strictly prohibited.  You do not have the right to
 * remove SugarCRM copyrights from the source code or user interface.
 *
 * All copies of the Covered Code must include on each user interface screen:
 *  (i) the "Powered by SugarCRM" logo and
 *  (ii) the SugarCRM copyright notice
 * in the same form as they appear in the distribution.  See full license for
 * requirements.
 *
 * Your Warranty, Limitations of liability and Indemnity are expressly stated
 * in the License.  Please refer to the License for the specific language
 * governing these rights and limitations under the License.  Portions created
 * by SugarCRM are Copyright (C) 2004-2009 SugarCRM, Inc.; All Rights Reserved.
 ********************************************************************************/
/**
 * THIS CLASS IS GENERATED BY MODULE BUILDER
 * PLEASE DO NOT CHANGE THIS CLASS
 * PLACE ANY CUSTOMIZATIONS IN Sites_Sites
 */

require_once('include/SugarObjects/templates/file/File.php');

class Sites_Sites_sugar extends File {
	var $new_schema = true;
	var $module_dir = 'Sites_Sites';
	var $object_name = 'Sites_Sites';
	var $table_name = 'sites_sites';
	var $importable = true;



		var $id;
		var $name;
		var $date_entered;
		var $date_modified;
		var $modified_user_id;
		var $modified_by_name;
		var $created_by;
		var $created_by_name;
		var $description;
		var $deleted;
		var $created_by_link;
		var $modified_user_link;
		var $team_id;
		var $team_name;
		var $team_link;
		var $assigned_user_id;
		var $assigned_user_name;
		var $assigned_user_link;
		var $document_name;
		var $filename;
		var $file_ext;
		var $file_mime_type;
		var $uploadfile;
		var $active_date;
		var $exp_date;
		var $category_id;
		var $subcategory_id;
		var $status_id;
		var $status;
		var $site_status;
		var $install_date;
		var $deinstall_date;
		var $dma_rank;
		var $county;
		var $station_num;
		var $retailer_id_num2;
		var $additech_id;
		var $address_city;
		var $address_state;
		var $address_postalcode;
		var $address_country;
		var $address;
		var $impressions;
		var $quoted_volume;
		var $quoted_transactions;
		var $population_density;
		var $average_household_income;
		var $restaurant_brand;
		var $volume_1209;
		var $volume_1109;
		var $volume_1009;
		var $cstore_type;
		var $twentyfour_seven;
		var $cstore_tv;
		var $hero_site;
		var $hero_site_relevance;
		var $volume_0909;
		var $volume_0809;
		var $volume_0709;
		var $site_tele_num;
		var $hardware_brand;
		var $market_text;
		var $dma_name_text;
		var $retailer_text;
		var $brand_text;
		var $restrictions;
		var $characteristics;
		var $store_manager;
		var $district_manager;
		var $legislative_citation;
		var $legislative_citation_desc;
		var $monday_open;
		var $monday_close;
		var $tuesday_open;
		var $tuesday_close;
		var $wednesday_open;
		var $wednesday_close;
		var $thursday_open;
		var $thursday_close;
		var $friday_open;
		var $friday_close;
		var $saturday_open;
		var $saturday_close;
		var $sunday_open;
		var $sunday_close;
		var $initial_site_serial_profile;
		var $installed_kit_number;
		var $connection_type;
		var $vandal_kit;
		var $tx_type;
		var $dual_tx_site;
		var $pumps_power_night;
		var $ladder_on_site;
		var $ladder_type;
		var $accessable_without_key;
		var $cabinet_vert_pos;
		var $cabinet_location;
		var $cabinet_type;
		var $modem_location;
		var $technical_characteristics;
		var $antenna_extension_number;
		var $player_type;
		var $gateway_ip;
		var $player1_ip;
		var $tx1_ip;
		var $tx2_ip;
		var $pdu_ip;
		var $pdu_type;
		var $jbm_serial;
		var $avo_firmware;
	
	
	function Sites_Sites_sugar(){	
		parent::File();
	}
	
	function bean_implements($interface){
		switch($interface){
			case 'ACL': return true;
		}
		return false;
}
		
}
?>