<?php
/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

$relationships = array (
  'agenc_agencies_modified_user' => 
  array (
    'id' => '59c1b534-0f8a-b5e2-6a92-51e81adaf107',
    'relationship_name' => 'agenc_agencies_modified_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'Agenc_Agencies',
    'rhs_table' => 'agenc_agencies',
    'rhs_key' => 'modified_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'agenc_agencies_created_by' => 
  array (
    'id' => '5abbbf29-1f9a-8365-fcc1-51e81abced11',
    'relationship_name' => 'agenc_agencies_created_by',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'Agenc_Agencies',
    'rhs_table' => 'agenc_agencies',
    'rhs_key' => 'created_by',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'agenc_agencies_assigned_user' => 
  array (
    'id' => '5cafc4be-4219-1a94-a966-51e81af6a1d1',
    'relationship_name' => 'agenc_agencies_assigned_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'Agenc_Agencies',
    'rhs_table' => 'agenc_agencies',
    'rhs_key' => 'assigned_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'agenc_agencies_accounts_3' => 
  array (
    'id' => 'daab9a24-9550-3596-8093-51e81a03738b',
    'relationship_name' => 'agenc_agencies_accounts_3',
    'lhs_module' => 'Agenc_Agencies',
    'lhs_table' => 'agenc_agencies',
    'lhs_key' => 'id',
    'rhs_module' => 'Accounts',
    'rhs_table' => 'accounts',
    'rhs_key' => 'id',
    'join_table' => 'agenc_agencs_accounts_3_c',
    'join_key_lhs' => 'agenc_agenf5b0gencies_ida',
    'join_key_rhs' => 'agenc_agen1c99ccounts_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'agenc_agencies_accounts' => 
  array (
    'id' => 'daab9ab9-ae62-24cd-e129-51e81a67f2eb',
    'relationship_name' => 'agenc_agencies_accounts',
    'lhs_module' => 'Agenc_Agencies',
    'lhs_table' => 'agenc_agencies',
    'lhs_key' => 'id',
    'rhs_module' => 'Accounts',
    'rhs_table' => 'accounts',
    'rhs_key' => 'id',
    'join_table' => 'agenc_agencies_accounts_c',
    'join_key_lhs' => 'agenc_agena415gencies_ida',
    'join_key_rhs' => 'agenc_agenc89eccounts_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'agenc_agencies_accounts_13' => 
  array (
    'id' => 'daab9b3f-3ed7-802d-c264-51e81a880bb7',
    'relationship_name' => 'agenc_agencies_accounts_13',
    'lhs_module' => 'Agenc_Agencies',
    'lhs_table' => 'agenc_agencies',
    'lhs_key' => 'id',
    'rhs_module' => 'Accounts',
    'rhs_table' => 'accounts',
    'rhs_key' => 'id',
    'join_table' => 'agenc_agenc_accounts_13_c',
    'join_key_lhs' => 'agenc_agenbc95gencies_ida',
    'join_key_rhs' => 'agenc_agen7d6fccounts_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'agenc_agencies_accounts_14' => 
  array (
    'id' => 'dc9f9ccf-6af8-5a7b-53d5-51e81a0841a7',
    'relationship_name' => 'agenc_agencies_accounts_14',
    'lhs_module' => 'Agenc_Agencies',
    'lhs_table' => 'agenc_agencies',
    'lhs_key' => 'id',
    'rhs_module' => 'Accounts',
    'rhs_table' => 'accounts',
    'rhs_key' => 'id',
    'join_table' => 'agenc_agenc_accounts_14_c',
    'join_key_lhs' => 'agenc_agen6509gencies_ida',
    'join_key_rhs' => 'agenc_agenc4efccounts_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'agenc_agencies_accounts_12' => 
  array (
    'id' => 'de93a950-26ae-f5cf-2305-51e81aca007e',
    'relationship_name' => 'agenc_agencies_accounts_12',
    'lhs_module' => 'Agenc_Agencies',
    'lhs_table' => 'agenc_agencies',
    'lhs_key' => 'id',
    'rhs_module' => 'Accounts',
    'rhs_table' => 'accounts',
    'rhs_key' => 'id',
    'join_table' => 'agenc_agenc_accounts_12_c',
    'join_key_lhs' => 'agenc_agen8489gencies_ida',
    'join_key_rhs' => 'agenc_agen9575ccounts_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'agenc_agencies_accounts_9' => 
  array (
    'id' => 'de93ad4b-5325-1546-2f25-51e81a9582ad',
    'relationship_name' => 'agenc_agencies_accounts_9',
    'lhs_module' => 'Agenc_Agencies',
    'lhs_table' => 'agenc_agencies',
    'lhs_key' => 'id',
    'rhs_module' => 'Accounts',
    'rhs_table' => 'accounts',
    'rhs_key' => 'id',
    'join_table' => 'agenc_agencs_accounts_9_c',
    'join_key_lhs' => 'agenc_agen0a8cgencies_ida',
    'join_key_rhs' => 'agenc_agen80d4ccounts_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'agenc_agencies_accounts_4' => 
  array (
    'id' => 'df8da3e2-f20d-f088-ca80-51e81ac377e5',
    'relationship_name' => 'agenc_agencies_accounts_4',
    'lhs_module' => 'Agenc_Agencies',
    'lhs_table' => 'agenc_agencies',
    'lhs_key' => 'id',
    'rhs_module' => 'Accounts',
    'rhs_table' => 'accounts',
    'rhs_key' => 'id',
    'join_table' => 'agenc_agencs_accounts_4_c',
    'join_key_lhs' => 'agenc_agenb32agencies_ida',
    'join_key_rhs' => 'agenc_agenab5dccounts_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'agenc_agencies_accounts_11' => 
  array (
    'id' => 'e087a63b-b565-d2e1-1099-51e81ae9fb17',
    'relationship_name' => 'agenc_agencies_accounts_11',
    'lhs_module' => 'Agenc_Agencies',
    'lhs_table' => 'agenc_agencies',
    'lhs_key' => 'id',
    'rhs_module' => 'Accounts',
    'rhs_table' => 'accounts',
    'rhs_key' => 'id',
    'join_table' => 'agenc_agenc_accounts_11_c',
    'join_key_lhs' => 'agenc_agenac1fgencies_ida',
    'join_key_rhs' => 'agenc_agen2119ccounts_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'agenc_agencies_accounts_7' => 
  array (
    'id' => 'e181bdd7-9713-6520-58e9-51e81a378424',
    'relationship_name' => 'agenc_agencies_accounts_7',
    'lhs_module' => 'Agenc_Agencies',
    'lhs_table' => 'agenc_agencies',
    'lhs_key' => 'id',
    'rhs_module' => 'Accounts',
    'rhs_table' => 'accounts',
    'rhs_key' => 'id',
    'join_table' => 'agenc_agencs_accounts_7_c',
    'join_key_lhs' => 'agenc_agen2a71gencies_ida',
    'join_key_rhs' => 'agenc_agenfee0ccounts_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'agenc_agencies_accounts_5' => 
  array (
    'id' => 'e181bf18-594e-0783-e43d-51e81a2b4e5b',
    'relationship_name' => 'agenc_agencies_accounts_5',
    'lhs_module' => 'Agenc_Agencies',
    'lhs_table' => 'agenc_agencies',
    'lhs_key' => 'id',
    'rhs_module' => 'Accounts',
    'rhs_table' => 'accounts',
    'rhs_key' => 'id',
    'join_table' => 'agenc_agencs_accounts_5_c',
    'join_key_lhs' => 'agenc_agen5ed9gencies_ida',
    'join_key_rhs' => 'agenc_agen49edccounts_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'agenc_agencies_accounts_8' => 
  array (
    'id' => 'e181bf1e-c566-2299-36ea-51e81a4082af',
    'relationship_name' => 'agenc_agencies_accounts_8',
    'lhs_module' => 'Agenc_Agencies',
    'lhs_table' => 'agenc_agencies',
    'lhs_key' => 'id',
    'rhs_module' => 'Accounts',
    'rhs_table' => 'accounts',
    'rhs_key' => 'id',
    'join_table' => 'agenc_agencs_accounts_8_c',
    'join_key_lhs' => 'agenc_agen0bbagencies_ida',
    'join_key_rhs' => 'agenc_agencaafccounts_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'agenc_agencies_accounts_10' => 
  array (
    'id' => 'e663c559-fc53-0678-43d3-51e81a4974f1',
    'relationship_name' => 'agenc_agencies_accounts_10',
    'lhs_module' => 'Agenc_Agencies',
    'lhs_table' => 'agenc_agencies',
    'lhs_key' => 'id',
    'rhs_module' => 'Accounts',
    'rhs_table' => 'accounts',
    'rhs_key' => 'id',
    'join_table' => 'agenc_agenc_accounts_10_c',
    'join_key_lhs' => 'agenc_agen6ab1gencies_ida',
    'join_key_rhs' => 'agenc_agen85e9ccounts_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'agenc_agencies_accounts_6' => 
  array (
    'id' => 'e663cc4e-f7bc-d82b-a94b-51e81a074a53',
    'relationship_name' => 'agenc_agencies_accounts_6',
    'lhs_module' => 'Agenc_Agencies',
    'lhs_table' => 'agenc_agencies',
    'lhs_key' => 'id',
    'rhs_module' => 'Accounts',
    'rhs_table' => 'accounts',
    'rhs_key' => 'id',
    'join_table' => 'agenc_agencs_accounts_6_c',
    'join_key_lhs' => 'agenc_agen7c5fgencies_ida',
    'join_key_rhs' => 'agenc_agen841dccounts_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'agenc_agencies_accounts_1' => 
  array (
    'rhs_label' => 'Advertisers',
    'lhs_label' => 'Agencies',
    'lhs_subpanel' => 'default',
    'rhs_subpanel' => 'default',
    'lhs_module' => 'Agenc_Agencies',
    'rhs_module' => 'Accounts',
    'relationship_type' => 'many-to-many',
    'readonly' => true,
    'deleted' => false,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
    'relationship_name' => 'agenc_agencies_accounts_1',
  ),
);