<?php
/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2013 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/


// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  0 => 
  array (
    'acceptable_sugar_versions' => 
    array (
      0 => '',
    ),
  ),
  1 => 
  array (
    'acceptable_sugar_flavors' => 
    array (
      0 => 'PRO',
    ),
  ),
  'readme' => '',
  'key' => 'props',
  'author' => '',
  'description' => '',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'Proposals',
  'published_date' => '2013-09-20 01:47:44',
  'type' => 'module',
  'version' => 1379641665,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'Proposals',
  'beans' => 
  array (
    0 => 
    array (
      'module' => 'props_Proposals',
      'class' => 'props_Proposals',
      'path' => 'modules/props_Proposals/props_Proposals.php',
      'tab' => true,
    ),
  ),
  'layoutdefs' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/props_proposals_opportunities_Opportunities.php',
      'to_module' => 'Opportunities',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/props_proposals_opportunities_props_Proposals.php',
      'to_module' => 'props_Proposals',
    ),
  ),
  'relationships' => 
  array (
    0 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/props_proposals_opportunitiesMetaData.php',
    ),
  ),
  'image_dir' => '<basepath>/icons',
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/modules/props_Proposals',
      'to' => 'modules/props_Proposals',
    ),
  ),
  'language' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'en_us',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'bg_BG',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'da_DK',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'de_DE',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'es_ES',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'fr_FR',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'hu_HU',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'it_it',
    ),
    8 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'lt_LT',
    ),
    9 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'ja_JP',
    ),
    10 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'nb_NO',
    ),
    11 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'nl_NL',
    ),
    12 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'pt_PT',
    ),
    13 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'ro_RO',
    ),
    14 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'ru_RU',
    ),
    15 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'sv_SE',
    ),
    16 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'tr_TR',
    ),
    17 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'zh_CN',
    ),
    18 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'cs_CZ',
    ),
    19 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'et_EE',
    ),
    20 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'he_IL',
    ),
    21 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'pl_PL',
    ),
    22 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'pt_BR',
    ),
    23 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'ca_ES',
    ),
    24 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'en_UK',
    ),
    25 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'sr_RS',
    ),
    26 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Opportunities.php',
      'to_module' => 'Opportunities',
      'language' => 'lv_LV',
    ),
    27 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/props_Proposals.php',
      'to_module' => 'props_Proposals',
      'language' => 'en_us',
    ),
    28 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/props_Proposals.php',
      'to_module' => 'props_Proposals',
      'language' => 'bg_BG',
    ),
    29 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/props_Proposals.php',
      'to_module' => 'props_Proposals',
      'language' => 'da_DK',
    ),
    30 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/props_Proposals.php',
      'to_module' => 'props_Proposals',
      'language' => 'de_DE',
    ),
    31 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/props_Proposals.php',
      'to_module' => 'props_Proposals',
      'language' => 'es_ES',
    ),
    32 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/props_Proposals.php',
      'to_module' => 'props_Proposals',
      'language' => 'fr_FR',
    ),
    33 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/props_Proposals.php',
      'to_module' => 'props_Proposals',
      'language' => 'hu_HU',
    ),
    34 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/props_Proposals.php',
      'to_module' => 'props_Proposals',
      'language' => 'it_it',
    ),
    35 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/props_Proposals.php',
      'to_module' => 'props_Proposals',
      'language' => 'lt_LT',
    ),
    36 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/props_Proposals.php',
      'to_module' => 'props_Proposals',
      'language' => 'ja_JP',
    ),
    37 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/props_Proposals.php',
      'to_module' => 'props_Proposals',
      'language' => 'nb_NO',
    ),
    38 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/props_Proposals.php',
      'to_module' => 'props_Proposals',
      'language' => 'nl_NL',
    ),
    39 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/props_Proposals.php',
      'to_module' => 'props_Proposals',
      'language' => 'pt_PT',
    ),
    40 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/props_Proposals.php',
      'to_module' => 'props_Proposals',
      'language' => 'ro_RO',
    ),
    41 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/props_Proposals.php',
      'to_module' => 'props_Proposals',
      'language' => 'ru_RU',
    ),
    42 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/props_Proposals.php',
      'to_module' => 'props_Proposals',
      'language' => 'sv_SE',
    ),
    43 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/props_Proposals.php',
      'to_module' => 'props_Proposals',
      'language' => 'tr_TR',
    ),
    44 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/props_Proposals.php',
      'to_module' => 'props_Proposals',
      'language' => 'zh_CN',
    ),
    45 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/props_Proposals.php',
      'to_module' => 'props_Proposals',
      'language' => 'cs_CZ',
    ),
    46 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/props_Proposals.php',
      'to_module' => 'props_Proposals',
      'language' => 'et_EE',
    ),
    47 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/props_Proposals.php',
      'to_module' => 'props_Proposals',
      'language' => 'he_IL',
    ),
    48 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/props_Proposals.php',
      'to_module' => 'props_Proposals',
      'language' => 'pl_PL',
    ),
    49 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/props_Proposals.php',
      'to_module' => 'props_Proposals',
      'language' => 'pt_BR',
    ),
    50 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/props_Proposals.php',
      'to_module' => 'props_Proposals',
      'language' => 'ca_ES',
    ),
    51 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/props_Proposals.php',
      'to_module' => 'props_Proposals',
      'language' => 'en_UK',
    ),
    52 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/props_Proposals.php',
      'to_module' => 'props_Proposals',
      'language' => 'sr_RS',
    ),
    53 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/props_Proposals.php',
      'to_module' => 'props_Proposals',
      'language' => 'lv_LV',
    ),
    54 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/en_us.lang.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
  ),
  'vardefs' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/props_proposals_opportunities_Opportunities.php',
      'to_module' => 'Opportunities',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/props_proposals_opportunities_props_Proposals.php',
      'to_module' => 'props_Proposals',
    ),
  ),
  'wireless_subpanels' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/wirelesslayoutdefs/props_proposals_opportunities_Opportunities.php',
      'to_module' => 'Opportunities',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/wirelesslayoutdefs/props_proposals_opportunities_props_Proposals.php',
      'to_module' => 'props_Proposals',
    ),
  ),
);